version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    volumes:
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
