services:
  backend:
    # This entrypoint calls the script AND passes "postgres" as the first argument.
    entrypoint: ["/usr/local/bin/wait-for-postgres.sh", "postgres"]
    # This command is passed to the script after the database is ready.
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # Re-add this volume for live code reloading
      - ./backend:/usr/src/app
      - ./test-reports:/usr/src/app/test-reports
    env_file:
      - ./.env
    environment:
      - PYTHONPATH=/usr/src/app
    depends_on:
      - postgres
    networks:
      - edrop-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app
    networks:
      - edrop-net
    depends_on:
      - backend

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - DB_TEST_DATABASE=${DB_TEST_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
    networks:
      - edrop-net

volumes:
  postgres-db:

networks:
  edrop-net:
    driver: bridge