services:
  backend:
    build: .
    ports:
      - "8000:8000" # Changed from 3000 to 8000
    env_file:
      - ./.env
    environment:
      - DB_HOST=postgres
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: