"""Update database schema for StoreProduct and related changes

Revision ID: 08639c703acc
Revises: 41e6a1b3aab6
Create Date: 2025-08-06 05:57:30.493794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08639c703acc'
down_revision: Union[str, Sequence[str], None] = '41e6a1b3aab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('product_ids', postgresql.ARRAY(sa.UUID()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'product_ids')
    # ### end Alembic commands ###
