"""Add created_at and updated_at to user and warehouse models

Revision ID: 0b57d96ea6d7
Revises: 8ef326b8ab23
Create Date: 2025-08-05 18:30:22.699149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b57d96ea6d7'
down_revision: Union[str, Sequence[str], None] = '8ef326b8ab23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('warehouses', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('warehouses', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouses', 'updated_at')
    op.drop_column('warehouses', 'created_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
