"""Add email and composite unique constraint to Customer model

Revision ID: 2b61cab718e3
Revises: 6dc74b7ff23e
Create Date: 2025-08-03 16:38:18.146123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b61cab718e3'
down_revision: Union[str, Sequence[str], None] = '6dc74b7ff23e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('email', sa.String(length=255), nullable=False))
    op.create_unique_constraint('uq_customer_email', 'customers', ['email'])
    op.create_unique_constraint('uq_customer_email_phone_number', 'customers', ['email', 'phone_number'])
    op.create_unique_constraint('uq_customer_phone_number', 'customers', ['phone_number'])
    op.create_unique_constraint(None, 'customers', ['email'])
    op.create_unique_constraint('uq_flat_number_rwa_id', 'flats', ['flat_number', 'rwa_id'])
    op.create_unique_constraint(None, 'orders', ['id'])
    op.drop_index(op.f('ix_rwas_name'), table_name='rwas')
    op.create_index(op.f('ix_rwas_name'), 'rwas', ['name'], unique=True)
    op.create_unique_constraint('uq_user_email', 'users', ['email'])
    op.create_unique_constraint('uq_vendor_name', 'vendors', ['business_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_vendor_name', 'vendors', type_='unique')
    op.drop_constraint('uq_user_email', 'users', type_='unique')
    op.drop_index(op.f('ix_rwas_name'), table_name='rwas')
    op.create_index(op.f('ix_rwas_name'), 'rwas', ['name'], unique=False)
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_constraint('uq_flat_number_rwa_id', 'flats', type_='unique')
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_constraint('uq_customer_phone_number', 'customers', type_='unique')
    op.drop_constraint('uq_customer_email_phone_number', 'customers', type_='unique')
    op.drop_constraint('uq_customer_email', 'customers', type_='unique')
    op.drop_column('customers', 'email')
    # ### end Alembic commands ###
