"""Sync user schema with database

Revision ID: 3327a6bc7e18
Revises: 4ae9144900c5
Create Date: 2025-08-04 06:44:45.750842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3327a6bc7e18'
down_revision: Union[str, Sequence[str], None] = '4ae9144900c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.String(length=50), nullable=False, server_default='pending'))
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('users', 'is_active')
    op.execute("UPDATE users SET status = 'ACTIVE' WHERE status = 'pending'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
