"""Remove vendor relationship from User model

Revision ID: 41e6a1b3aab6
Revises: cc639e64c856
Create Date: 2025-08-05 20:52:03.016306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41e6a1b3aab6'
down_revision: Union[str, Sequence[str], None] = 'cc639e64c856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
