"""add milestone table

Revision ID: 4f35004020d6
Revises: 60fbeff4edd5
Create Date: 2025-08-03 13:50:16.437396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f35004020d6'
down_revision: Union[str, Sequence[str], None] = '60fbeff4edd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_profiles_business_name'), table_name='vendor_profiles')
    op.drop_table('vendor_profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('business_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.NUMERIC(precision=10, scale=7), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.NUMERIC(precision=10, scale=7), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_vendor_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('vendor_profiles_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('vendor_profiles_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_vendor_profiles_business_name'), 'vendor_profiles', ['business_name'], unique=False)
    # ### end Alembic commands ###
