"""Rename_vendor_profile_to_vendor

Revision ID: 5e32974f5007
Revises: d9b3b8181baa
Create Date: 2025-07-24 12:40:36.029206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e32974f5007'
down_revision: Union[str, Sequence[str], None] = 'd9b3b8181baa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_vendors_business_name'), 'vendors', ['business_name'], unique=False)
    op.drop_index(op.f('ix_vendor_profiles_business_name'), table_name='vendor_profiles')
    op.drop_table('vendor_profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('business_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.NUMERIC(precision=10, scale=7), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.NUMERIC(precision=10, scale=7), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('vendor_profiles_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('vendor_profiles_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('vendor_profiles_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_vendor_profiles_business_name'), 'vendor_profiles', ['business_name'], unique=False)
    op.drop_index(op.f('ix_vendors_business_name'), table_name='vendors')
    op.drop_table('vendors')
    # ### end Alembic commands ###
