"""add crate table

Revision ID: 62bf11b2f610
Revises: f1af02ac48cb
Create Date: 2025-08-06 17:30:56.237880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62bf11b2f610'
down_revision: Union[str, Sequence[str], None] = 'f1af02ac48cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    vendortype_enum = sa.Enum('SKU', 'FLAT', name='vendortype')
    vendortype_enum.create(op.get_bind())

    vendorstatus_enum = sa.Enum('ACTIVE', 'INACTIVE', 'KYC_PENDING', name='vendorstatus')
    vendorstatus_enum.create(op.get_bind())

    op.execute("""
        ALTER TABLE vendors ALTER COLUMN vendor_type TYPE vendortype USING vendor_type::text::vendortype
    """)

    op.execute("""
        ALTER TABLE vendors ALTER COLUMN vendor_status TYPE vendorstatus USING vendor_status::text::vendorstatus
    """)

    op.alter_column('vendors', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('vendors', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_vendors_email'), 'vendors', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendors_email'), table_name='vendors')
    op.alter_column('vendors', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('vendors', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('vendors', 'vendor_status',
               existing_type=sa.Enum('ACTIVE', 'INACTIVE', 'KYC_PENDING', name='vendorstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('vendors', 'vendor_type',
               existing_type=sa.Enum('SKU', 'FLAT', name='vendortype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    vendortype_enum = sa.Enum('SKU', 'FLAT', name='vendortype')
    vendortype_enum.drop(op.get_bind())
    # ### end Alembic commands ###
