"""Fix model import order and resolve conflicts

Revision ID: 68dfc10dd979
Revises: 85f4bd7e59f8
Create Date: 2025-08-06 18:22:27.276913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68dfc10dd979'
down_revision: Union[str, Sequence[str], None] = '85f4bd7e59f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
