"""Fix_product_vendor_foreign_key

Revision ID: 6c6db99e7a5d
Revises: d9b3b8181baa
Create Date: 2025-07-24 13:15:48.761977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '6c6db99e7a5d'
down_revision: Union[str, Sequence[str], None] = 'd9b3b8181baa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'sku',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    inspector = inspect(op.get_bind())
    indexes = inspector.get_indexes('products')
    index_names = [index['name'] for index in indexes]

    if 'ix_products_sku' in index_names:
        op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.create_unique_constraint('uq_products_sku', 'products', ['sku'])
    op.drop_constraint('products_vendor_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key('fk_products_vendor_id', 'products', 'vendors', ['vendor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_products_vendor_id', 'products', type_='foreignkey')
    op.create_foreign_key('products_vendor_id_fkey', 'products', 'users', ['vendor_id'], ['id'])
    op.drop_constraint('uq_products_sku', 'products', type_='unique')
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.alter_column('products', 'sku',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
