"""Add unique constraint to Warehouse table

Revision ID: 6dc74b7ff23e
Revises: fbc49f2fd9d0
Create Date: 2025-08-03 16:23:14.015640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dc74b7ff23e'
down_revision: Union[str, Sequence[str], None] = 'fbc49f2fd9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_warehouse_name_address', 'warehouses', ['name', 'address'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_warehouse_name_address', 'warehouses', type_='unique')
    # ### end Alembic commands ###
