"""Add new fields to warehouse model

Revision ID: 6e0e74e00f41
Revises: 71b25fd57d71
Create Date: 2025-08-02 21:24:40.321758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e0e74e00f41'
down_revision: Union[str, Sequence[str], None] = '71b25fd57d71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    warehouse_status_enum = sa.Enum('ACTIVE', 'INACTIVE', 'NEAR_CAPACITY', name='warehouse_status_enum')
    warehouse_status_enum.create(op.get_bind())
    op.add_column('warehouses', sa.Column('status', warehouse_status_enum, nullable=False))
    op.add_column('warehouses', sa.Column('size_sqft', sa.Integer(), nullable=False))
    op.add_column('warehouses', sa.Column('utilization_pct', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('warehouses', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('warehouses', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('warehouses', sa.Column('capacity_units', sa.Integer(), nullable=True))
    op.add_column('warehouses', sa.Column('operations_time', sa.String(length=100), nullable=True))
    op.add_column('warehouses', sa.Column('contact_phone', sa.String(length=20), nullable=True))
    op.add_column('warehouses', sa.Column('contact_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouses', 'contact_email')
    op.drop_column('warehouses', 'contact_phone')
    op.drop_column('warehouses', 'operations_time')
    op.drop_column('warehouses', 'capacity_units')
    op.drop_column('warehouses', 'end_date')
    op.drop_column('warehouses', 'start_date')
    op.drop_column('warehouses', 'utilization_pct')
    op.drop_column('warehouses', 'size_sqft')
    op.drop_column('warehouses', 'status')
    warehouse_status_enum = sa.Enum('ACTIVE', 'INACTIVE', 'NEAR_CAPACITY', name='warehouse_status_enum')
    warehouse_status_enum.drop(op.get_bind())
    # ### end Alembic commands ###
