"""Remove extend_existing from Store model

Revision ID: 85f4bd7e59f8
Revises: 13f0b8651e80
Create Date: 2025-08-06 18:19:09.801253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85f4bd7e59f8'
down_revision: Union[str, Sequence[str], None] = '13f0b8651e80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('qr_code', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'IN_USE', 'RESERVED', 'DAMAGED', 'INACTIVE', name='cratestatus'), nullable=False),
    sa.Column('type', sa.Enum('STANDARD', 'REFRIGERATED', 'LARGE', name='cratetype'), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crates_name'), 'crates', ['name'], unique=False)
    op.create_index(op.f('ix_crates_qr_code'), 'crates', ['qr_code'], unique=True)
    op.create_table('store_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('available_qty', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('bin_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_products_id'), 'store_products', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_products_id'), table_name='store_products')
    op.drop_table('store_products')
    op.drop_index(op.f('ix_crates_qr_code'), table_name='crates')
    op.drop_index(op.f('ix_crates_name'), table_name='crates')
    op.drop_table('crates')
    # ### end Alembic commands ###
