"""Add milestone_value column to Milestone model

Revision ID: 9005bc42adf1
Revises: 2b61cab718e3
Create Date: 2025-08-03 16:53:38.456842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9005bc42adf1'
down_revision: Union[str, Sequence[str], None] = '2b61cab718e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestones', sa.Column('milestone_value', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('milestones', 'milestone_value')
    # ### end Alembic commands ###
