"""add_notes_column_to_communities

Revision ID: 91d0b8359bc5
Revises: aecd219bf620
Create Date: 2025-08-23 18:29:41.680542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91d0b8359bc5'
down_revision: Union[str, Sequence[str], None] = 'aecd219bf620'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.add_column('communities', sa.Column('notes', sa.Text(), nullable=True))
    op.drop_column('communities', 'community_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communities', sa.Column('community_type', postgresql.ENUM('COMMUNITY', 'INDIVIDUAL', name='residencetype'), autoincrement=False, nullable=False))
    op.drop_column('communities', 'notes')
    op.create_index(op.f('ix_addresses_id'), 'addresses', ['id'], unique=False)
    # ### end Alembic commands ###
