"""update user model with status, role enum, and last login

Revision ID: a2c63d4d9d33
Revises: 04446ed3b01c
Create Date: 2025-08-04 06:08:59.394180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2c63d4d9d33'
down_revision: Union[str, Sequence[str], None] = '04446ed3b01c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
