"""Update vendor and warehouse milestone logic

Revision ID: a7302eaf978f
Revises: f5805e5e66c5
Create Date: 2025-08-05 18:24:57.501711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7302eaf978f'
down_revision: Union[str, Sequence[str], None] = 'f5805e5e66c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('registered_name', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('vendor_type', sa.String(), nullable=False))
    op.add_column('vendors', sa.Column('email', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('registered_address', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('vendor_status', sa.String(), nullable=False))
    op.add_column('vendors', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('vendors', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'updated_at')
    op.drop_column('vendors', 'created_at')
    op.drop_column('vendors', 'vendor_status')
    op.drop_column('vendors', 'registered_address')
    op.drop_column('vendors', 'phone_number')
    op.drop_column('vendors', 'email')
    op.drop_column('vendors', 'vendor_type')
    op.drop_column('vendors', 'registered_name')
    # ### end Alembic commands ###
