"""Update vendor and store models

Revision ID: c680703151e6
Revises: f4b47b8bcbde
Create Date: 2025-08-05 20:32:40.442436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c680703151e6'
down_revision: Union[str, Sequence[str], None] = 'f4b47b8bcbde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('password', sa.String(), nullable=False))
    op.drop_constraint(op.f('vendors_user_id_key'), 'vendors', type_='unique')
    op.drop_constraint(op.f('vendors_user_id_fkey'), 'vendors', type_='foreignkey')
    op.drop_column('vendors', 'latitude')
    op.drop_column('vendors', 'longitude')
    op.drop_column('vendors', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('vendors', sa.Column('longitude', sa.NUMERIC(precision=10, scale=7), autoincrement=False, nullable=True))
    op.add_column('vendors', sa.Column('latitude', sa.NUMERIC(precision=10, scale=7), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('vendors_user_id_fkey'), 'vendors', 'users', ['user_id'], ['id'])
    op.create_unique_constraint(op.f('vendors_user_id_key'), 'vendors', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('vendors', 'password')
    # ### end Alembic commands ###
