"""Add_lat_long_to_rwas

Revision ID: cfcce025c785
Revises: 5e32974f5007
Create Date: 2025-07-24 12:54:20.670076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfcce025c785'
down_revision: Union[str, Sequence[str], None] = '5e32974f5007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rwas', sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True))
    op.add_column('rwas', sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True))
    op.alter_column('rwas', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rwas', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('rwas', 'longitude')
    op.drop_column('rwas', 'latitude')
    # ### end Alembic commands ###
