"""Definitively fix model loading conflict

Revision ID: e068a58ad49e
Revises: 68dfc10dd979
Create Date: 2025-08-06 18:26:05.353279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e068a58ad49e'
down_revision: Union[str, Sequence[str], None] = '68dfc10dd979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
