"""enhance_customer_model_with_status_timestamps_and_location

Revision ID: f69d32adfd25
Revises: 2e0b83e20869
Create Date: 2025-08-23 18:02:37.109169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f69d32adfd25'
down_revision: Union[str, Sequence[str], None] = '2e0b83e20869'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First, handle the communities blocks column conversion
    # We need to manually convert TEXT to ARRAY using USING clause
    op.execute("ALTER TABLE communities ALTER COLUMN blocks TYPE VARCHAR[] USING string_to_array(blocks, ',')::VARCHAR[]")
    
    # Create the enum type first
    op.execute("CREATE TYPE customerstatus AS ENUM ('ACTIVE', 'INACTIVE', 'SUSPENDED')")
    
    # Add new customer columns
    op.add_column('customers', sa.Column('block', sa.String(length=100), nullable=True))
    op.add_column('customers', sa.Column('flat_number', sa.String(length=50), nullable=True))
    op.add_column('customers', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='customerstatus'), nullable=False, server_default='ACTIVE'))
    op.add_column('customers', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('customers', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('customers', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    
    # Update constraints
    op.drop_constraint(op.f('uq_customer_email_phone_number'), 'customers', type_='unique')
    op.create_unique_constraint('uq_customer_location', 'customers', ['community_id', 'block', 'flat_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_customer_location', 'customers', type_='unique')
    op.create_unique_constraint(op.f('uq_customer_email_phone_number'), 'customers', ['email', 'phone_number'], postgresql_nulls_not_distinct=False)
    op.drop_column('customers', 'updated_at')
    op.drop_column('customers', 'created_at')
    op.drop_column('customers', 'notes')
    op.drop_column('customers', 'status')
    op.drop_column('customers', 'flat_number')
    op.drop_column('customers', 'block')
    
    # Drop the enum type
    op.execute("DROP TYPE IF EXISTS customerstatus")
    
    # Convert array back to text
    op.execute("ALTER TABLE communities ALTER COLUMN blocks TYPE TEXT USING array_to_string(blocks, ',')")
    # ### end Alembic commands ###
