"""Add event_type and entity_type to Milestone model

Revision ID: fbc49f2fd9d0
Revises: da497007c497
Create Date: 2025-08-03 15:58:56.176733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fbc49f2fd9d0'
down_revision: Union[str, Sequence[str], None] = 'da497007c497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milestones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('milestone_type', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('related_entity_id', sa.String(length=255), nullable=True),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Enum('CUSTOMER_COUNT', 'ORDER_COUNT', 'VENDOR_COUNT', 'WAREHOUSE_CREATED', 'CUSTOMER_ORDER_COUNT', 'WAREHOUSE_ANNIVERSARY', name='milestoneeventtype'), nullable=False),
    sa.Column('entity_type', sa.Enum('CUSTOMER', 'ORDER', 'VENDOR', 'WAREHOUSE', 'SYSTEM', name='milestoneentitytype'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milestones_milestone_type'), 'milestones', ['milestone_type'], unique=False)
    op.drop_table('milestone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milestone',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('entity_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('milestone_value', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('auto_triggered', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('milestone_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('milestone_pkey'))
    )
    op.drop_index(op.f('ix_milestones_milestone_type'), table_name='milestones')
    op.drop_table('milestones')
    # ### end Alembic commands ###
